.TH GPT 1 "2025-04-06" "Toolkit" "User Commands"
.SH NAME
gpt \- A simple OpenAI text generation utility
.SH SYNOPSIS
.B gpt
[\fIOPTIONS\fR]
.SH DESCRIPTION
A simple OpenAI text generation utility
.SH OPTIONS
.TP
.B \-\-help
Show help message and exit.
.TP
.B \-\-version
Show version information and exit.
.SH EXAMPLES
.PP
gpt --help
.SH SEE ALSO
.BR toolkit-help (1)