.TH DOCX2MD 1 "2025-04-06" "Toolkit" "User Commands"
.SH NAME
docx2md \- Convert Word .docx files to Markdown
.SH SYNOPSIS
.B docx2md
[\fIOPTIONS\fR]
.SH DESCRIPTION
Convert Word .docx files to Markdown
.SH OPTIONS
.TP
.B \-\-help
Show help message and exit.
.TP
.B \-\-version
Show version information and exit.
.SH EXAMPLES
.PP
docx2md --help
.SH SEE ALSO
.BR toolkit-help (1)