.TH TOOLKIT 1 "2025-04-06" "Toolkit" "User Commands"
.SH NAME
toolkit \- Manage and discover toolkit utilities
.SH SYNOPSIS
.B toolkit
[\fIOPTIONS\fR]
.SH DESCRIPTION
Manage and discover toolkit utilities
.SH OPTIONS
.TP
.B \-\-help
Show help message and exit.
.TP
.B \-\-version
Show version information and exit.
.SH EXAMPLES
.PP
toolkit --help
.SH SEE ALSO
.BR toolkit-help (1)